language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "3.8"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev # provides unbuffer utility
      - "python-lxml"
      - "python-simplejson"
      - "python-serial"
      - "python-yaml"

stages:
  - test

jobs:
  include:
    # Test separately: base
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="odoo/odoo" MAKEPOT=1 INCLUDE="base"
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="OCA/OCB" INCLUDE="base"
    # Test separately: board
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="odoo/odoo" MAKEPOT=1 INCLUDE="board"
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="OCA/OCB" INCLUDE="board"
    # Test all other addons together
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="odoo/odoo" MAKEPOT=1 EXCLUDE="base,board"
    - stage: test
      env:
        - TESTS=1 ODOO_REPO="OCA/OCB" EXCLUDE="base,board"
env:
  global:
    - VERSION="15.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
    - WKHTMLTOPDF_VERSION="0.12.5"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git
    ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
