{
    'name': 'Open Academy',
    'summary': """
        Odoo training""",
    'application': True,
    'license': 'LGPL-3',
    'author': 'Odoo Community Association (OCA)',
    'website': 'https://github.com/rolandojduartem/OpenAcademy',
    'category': 'Uncategorized',
    'version': '15.0.1.0.0',
    'depends': [
        'base',
        'board',
    ],
    'data': [
        'data/res_group.xml',
        'data/ir_rule.xml',
        'security/ir.model.access.csv',
        'views/partner.xml',
        'views/course.xml',
        'views/session.xml',
        'report/open_academy_report_views.xml',
        'data/ir_ui_menu.xml',
        'wizards/assign_attendee_sessions.xml',
        'report/session_templates.xml',
        'report/session_reports.xml',
    ],
    'demo': [
        'demo/category.xml',
        'demo/res_partner.xml',
        'demo/res_users.xml',
        'demo/course.xml',
        'demo/session.xml',
    ],
}
